[tox]
isolated_build = True
envlist = py310,py311,py312,py313,py314

[testenv]
deps =
    black
    pytest
    pylint
commands =
#    black --check eurlex -vv
    pytest -m "not integration" .
    pylint eurlex

[testenv:integration]
deps =
    pytest
commands =
    pytest -m integration .

[testenv:linting]
deps = pre-commit
commands = pre-commit run --all-files --show-diff-on-failure

[testenv:coverage]
deps =
    pytest
    coverage
commands =
    coverage run --source=eurlex --branch -m pytest -m "not integration"
    coverage report -m
    coverage xml

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312, linting
    3.13: py313
    3.14: py314
